use csegdb;

drop table if exists t2_cmip6_MIP_tier1_groups;

create table t2_cmip6_MIP_tier1_groups(
       `id` INTEGER AUTO_INCREMENT NOT NULL,	
       `name` VARCHAR(40),
       primary key (id));	

insert into t2_cmip6_MIP_tier1_groups (name)
values 
('HIST'),
('NTCFRESP'),
('WMFORC'),
('esm1pcbgc'),
('esmssp5-85'),
('amip4K'),
('amipFuture'),
('amip4xCO2'),
('amip'),
('aquaControl'),
('aqua4K'),
('aqua4xCO2'),
('histALL'),
('histNAT'),
('histGHG'),
('histAER_histAERchem'),
('DCPP-A_hindcasts'),
('DCPP-B_forcasts'),
('DCPP-C_hiatus'),
('DCPP-C_volcanoes'),
('AMIPFuture4xCO2'),
('wind'),
('heat'),
('water'),
('G1ext'),
('G6sulfate'),
('G6solar'),
('g7cirrus'),
('AMIP20C'),
('Forced_Atmos_Land'),
('piControlwithism'),
('1pctCo2withism'),
('LMIP-Hist'),
('LFMIP-Hist-AOGCM'),
('LFMIP-AOGCM'),
('LND_noLULCC_hist'),
('CPL_1percentDF'),
('CPL_noLULCC_hist_conc'),
('CPL_landpolicy_fut_emis'),
('CORE-II'),
('OCN_CFC_SF6'),
('OCNGBC_FORCE_hist'),
('OCNGBC_FORCE_ctrl'),
('PDR_FULL'),
('LGM'),
('midHolocene'),
('past1000'),
('PlioExp'),
('LIG'),
('RFMIP-IRF-GHG'),
('RFMIP-IRF-AER'),
('RFMIP-ERF-PI-Cntrl'),
('RFMIP-ERF-4xCO2'),
('RFMIP-ERF-Anthro'),
('RFMIP-ERF-GHG'),
('RFMIP-ERF-AER'),
('RFMIP-ERF-LU'),
('RFMIP-Hist-All'),
('SSP5_85'),
('SSPX_60'),
('SSP1_26'),
('VolLongS100EQ'),
('VolShort20EQfull');
